# Generated by Django 2.0.13 on 2019-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feed_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=120)),
                ('time', models.CharField(max_length=120)),
                ('class_name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('no_lec', models.CharField(max_length=120)),
                ('roll_no', models.CharField(max_length=120)),
                ('tech_name', models.CharField(max_length=120)),
            ],
        ),
    ]
